apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 0.3.81
    helm:
      releaseName: home-assistant
      values: |
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: "2026.9.2"
        replicaCount: 1
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        service:
          main:
            type: ClusterIP
            port: 8080
        ingress:
          enabled: true
          hosts:
            - host: home-assistant.lan
              paths:
                - path: /
                  pathType: Prefix
        podAnnotations:
          configmap.reloader.stakater.com/reload: "home-assistant-dashboard-minimal"
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 512Mi
        configuration:
          enabled: true
          forceInit: true
          trusted_proxies:
            - 10.42.0.0/16
            - 192.168.0.0/16
          templateConfig: |
            default_config:
            frontend:
              themes: !include_dir_merge_named themes
            automation: !include automations.yaml
            script: !include scripts.yaml
            scene: !include scenes.yaml

            lovelace:
              mode: storage
              resources:
                - url: https://cdn.jsdelivr.net/npm/lovelace-mushroom@4.3.1/dist/mushroom.js
                  type: module
              dashboards:
                minimal:
                  mode: yaml
                  title: Daily
                  icon: mdi:home-heart
                  show_in_sidebar: true
                  filename: dashboards/minimal.yaml
        additionalVolumes:
          - name: dashboard-minimal
            configMap:
              name: home-assistant-dashboard-minimal
        additionalMounts:
          - name: dashboard-minimal
            mountPath: /config/dashboards/minimal.yaml
            subPath: minimal.yaml
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 5Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
